version: '3.5'

# Services
services:

  # PHP FPM Service
  php:
    container_name: phpcode
    build:
      dockerfile: ./docker/php/dockerfile
      context: .
    volumes:
      - './:/var/www/html'
    depends_on:
      - mariadb

  # Nginx Service
  nginx:
    container_name: website
    image: nginx:latest
    ports:
      - 8080:80
    links:
      - 'php'
    volumes:
      - './:/var/www/html'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php

  # MariaDB Service
  mariadb:
    container_name: database
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: website
      MYSQL_USER: website_user
      MYSQL_PASSWORD: St3rkW8woord!
      MYSQL_ROOT_PASSWORD: 4dy5qwturag#!sie
    ports:
      - 3307:3306
    volumes:
      - './docker/mysqldata:/var/lib/mysql'

# Volumes
volumes:
  mysqldata: